### ISSUE TITLE
Script compilation throws System.PlatformNotSupportedException on linux

### ISSUE THREAD

**Issue by riccardobl** [effekseer/Effekseer#507]
On startup, the editor throws the following errors on linux
```
CSharp Compile Exception : /opt/local/effekseer/Tool/scripts/export/glTF.cs
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at Effekseer.Script.Compiler.Compile(String path, Object& compiled, String& error) in /home/runner/work/Effekseer/Effekseer/Dev/Editor/EffekseerCore/Script/Compiler.cs:line 91
CSharp Compile Exception : /opt/local/effekseer/Tool/scripts/export/Default.cs
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at Effekseer.Script.Compiler.Compile(String path, Object& compiled, String& error) in /home/runner/work/Effekseer/Effekseer/Dev/Editor/EffekseerCore/Script/Compiler.cs:line 91
CSharp Compile Exception : /opt/local/effekseer/Tool/scripts/export/EfkPkg.cs
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at Effekseer.Script.Compiler.Compile(String path, Object& compiled, String& error) in /home/runner/work/Effekseer/Effekseer/Dev/Editor/EffekseerCore/Script/Compiler.cs:line 91
CSharp Compile Exception : /opt/local/effekseer/Tool/scripts/export/glb.cs
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at Effekseer.Script.Compiler.Compile(String path, Object& compiled, String& error) in /home/runner/work/Effekseer/Effekseer/Dev/Editor/EffekseerCore/Script/Compiler.cs:line 91
```
and the scripts are not compiled.
This seems to be caused by CodeDom not being implemented in the linux runtime.

**Comment by durswd** [comment]
It seem that making scripts disabled is better.

**Comment by riccardobl** [comment]
I've found that there is this crossplatform alternative
https://www.cs-script.net/
not being a C# dev, though, i don't know if replacing codedom with this would require a considerable effort
