### ISSUE TITLE
[Linux] error compiler SoundAL

### ISSUE THREAD

**Issue by UnknownS1024** [effekseer/Effekseer#641]
distribution `OpenSUSE`

gcc (SUSE Linux) 10.2.1 20210303 [revision 85977f624a34eac309f9d77a58164553dfc82975]
python 3.8.8
cmake 3.19.6

errors

```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:~/git/Effekseer> python3 build.py
cmake .. -G Ninja -DBUILD_VIEWER=ON
CMake Deprecation Warning at Dev/Cpp/EffekseerSoundAL/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at Dev/Cpp/EffekseerSoundOSMixer/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Build spdlog: 1.5.0
-- Build type: Release
CMake Deprecation Warning at Dev/Cpp/3rdParty/AltseedRHI/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at Dev/Cpp/3rdParty/AltseedRHI/src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
CMake Warning (dev) at Dev/Cpp/CMakeLists.txt:174 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "ExternalProject_glew" of target "AltseedRHI" does
  not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/xxxxxxx/git/Effekseer/build
cmake --build . --config Release
[6/113] Building CXX object Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp.o
FAILED: Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp.o 
/usr/bin/clang++ -D__EFFEKSEER_RENDERER_INTERNAL_LOADER__ -D__EFFEKSEER_USE_LIBPNG__ -I../Dev/Cpp/Effekseer -I../Dev/Cpp/include -I../Dev/Cpp/EffekseerSoundAL/../include -O3 -DNDEBUG -fPIC -std=gnu++17 -MD -MT Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp.o -MF Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp.o.d -o Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp.o -c ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundImplemented.h:8:
../Dev/Cpp/EffekseerSoundAL/EffekseerSound/../EffekseerSoundAL.h:13:10: fatal error: 'AL/al.h' file not found
#include <AL/al.h>
         ^~~~~~~~~
1 error generated.
[7/113] Building CXX object Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.Sound.cpp.o
FAILED: Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.Sound.cpp.o 
/usr/bin/clang++ -D__EFFEKSEER_RENDERER_INTERNAL_LOADER__ -D__EFFEKSEER_USE_LIBPNG__ -I../Dev/Cpp/Effekseer -I../Dev/Cpp/include -I../Dev/Cpp/EffekseerSoundAL/../include -O3 -DNDEBUG -fPIC -std=gnu++17 -MD -MT Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.Sound.cpp.o -MF Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.Sound.cpp.o.d -o Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.Sound.cpp.o -c ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.Sound.cpp
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.Sound.cpp:5:
../Dev/Cpp/EffekseerSoundAL/EffekseerSound/../EffekseerSoundAL.h:13:10: fatal error: 'AL/al.h' file not found
#include <AL/al.h>
         ^~~~~~~~~
1 error generated.
[8/113] Building CXX object Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp.o
FAILED: Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp.o 
/usr/bin/clang++ -D__EFFEKSEER_RENDERER_INTERNAL_LOADER__ -D__EFFEKSEER_USE_LIBPNG__ -I../Dev/Cpp/Effekseer -I../Dev/Cpp/include -I../Dev/Cpp/EffekseerSoundAL/../include -O3 -DNDEBUG -fPIC -std=gnu++17 -MD -MT Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp.o -MF Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp.o.d -o Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp.o -c ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundVoice.cpp:6:
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundImplemented.h:8:
../Dev/Cpp/EffekseerSoundAL/EffekseerSound/../EffekseerSoundAL.h:13:10: fatal error: 'AL/al.h' file not found
#include <AL/al.h>
         ^~~~~~~~~
1 error generated.
[9/113] Building CXX object Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp.o
FAILED: Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp.o 
/usr/bin/clang++ -D__EFFEKSEER_RENDERER_INTERNAL_LOADER__ -D__EFFEKSEER_USE_LIBPNG__ -I../Dev/Cpp/Effekseer -I../Dev/Cpp/include -I../Dev/Cpp/EffekseerSoundAL/../include -O3 -DNDEBUG -fPIC -std=gnu++17 -MD -MT Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp.o -MF Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp.o.d -o Dev/Cpp/EffekseerSoundAL/CMakeFiles/EffekseerSoundAL.dir/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp.o -c ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundAL/EffekseerSound/EffekseerSoundAL.SoundImplemented.h:8:
../Dev/Cpp/EffekseerSoundAL/EffekseerSound/../EffekseerSoundAL.h:13:10: fatal error: 'AL/al.h' file not found
#include <AL/al.h>
         ^~~~~~~~~
1 error generated.
[10/113] Building CXX object Dev/Cpp/EffekseerSoundOSMixer/CMakeFiles/EffekseerSoundOSMixer.dir/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp.o
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:51:7: warning: 'Destroy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void Destroy();
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:102:15: note: overridden virtual function is here
        virtual void Destroy() = 0;
                     ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:55:7: warning: 'SetListener' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void SetListener( const ::Effekseer::Vector3D& pos, 
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:112:15: note: overridden virtual function is here
        virtual void SetListener( const ::Effekseer::Vector3D& pos, 
                     ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:58:7: warning: 'Update' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void Update();
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:107:15: note: overridden virtual function is here
        virtual void Update() = 0;
                     ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:60:30: warning: 'CreateSoundPlayer' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        ::Effekseer::SoundPlayerRef CreateSoundPlayer();
                                    ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:118:38: note: overridden virtual function is here
        virtual ::Effekseer::SoundPlayerRef CreateSoundPlayer() = 0;
                                            ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:62:30: warning: 'CreateSoundLoader' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        ::Effekseer::SoundLoaderRef CreateSoundLoader( ::Effekseer::FileInterface* fileInterface = NULL );
                                    ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:123:38: note: overridden virtual function is here
        virtual ::Effekseer::SoundLoaderRef CreateSoundLoader( ::Effekseer::FileInterface* fileInterface = NULL ) = 0;
                                            ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundPlayer.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:66:7: warning: 'SetMute' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void SetMute( bool mute );
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:128:15: note: overridden virtual function is here
        virtual void SetMute( bool mute ) = 0;
                     ^
6 warnings generated.
[11/113] Building CXX object Dev/Cpp/EffekseerSoundOSMixer/CMakeFiles/EffekseerSoundOSMixer.dir/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp.o
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:51:7: warning: 'Destroy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void Destroy();
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:102:15: note: overridden virtual function is here
        virtual void Destroy() = 0;
                     ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:55:7: warning: 'SetListener' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void SetListener( const ::Effekseer::Vector3D& pos, 
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:112:15: note: overridden virtual function is here
        virtual void SetListener( const ::Effekseer::Vector3D& pos, 
                     ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:58:7: warning: 'Update' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void Update();
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:107:15: note: overridden virtual function is here
        virtual void Update() = 0;
                     ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:60:30: warning: 'CreateSoundPlayer' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        ::Effekseer::SoundPlayerRef CreateSoundPlayer();
                                    ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:118:38: note: overridden virtual function is here
        virtual ::Effekseer::SoundPlayerRef CreateSoundPlayer() = 0;
                                            ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:62:30: warning: 'CreateSoundLoader' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        ::Effekseer::SoundLoaderRef CreateSoundLoader( ::Effekseer::FileInterface* fileInterface = NULL );
                                    ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:123:38: note: overridden virtual function is here
        virtual ::Effekseer::SoundLoaderRef CreateSoundLoader( ::Effekseer::FileInterface* fileInterface = NULL ) = 0;
                                            ^
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.cpp:5:
In file included from ../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundLoader.h:9:
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/EffekseerSoundOSMixer.SoundImplemented.h:66:7: warning: 'SetMute' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void SetMute( bool mute );
             ^
../Dev/Cpp/EffekseerSoundOSMixer/EffekseerSound/../EffekseerSoundOSMixer.h:128:15: note: overridden virtual function is here
        virtual void SetMute( bool mute ) = 0;
                     ^
6 warnings generated.
[15/113] Building CXX object Dev/Cpp/EditorCommon/CMakeFiles/EditorCommon.dir/IO/DefaultFileReader.cpp.o
ninja: build stopped: subcommand failed.
Failed cmake --build . --config Release
Traceback (most recent call last):
  File "build.py", line 188, in <module>
    call('cmake --build . --config Release')
  File "build.py", line 21, in call
    raise Exception
Exception
```

compiler i don't like wasting time reason want to officially linux launch Effekseer without compilation everything will be fine :)

**Comment by durswd** [comment]
Did you install dependencies?

https://github.com/effekseer/Effekseer/blob/master/docs/Development/HowToBuild.md#linux

**Comment by UnknownS1024** [comment]
yes already installed but two exceptions

![image](https://user-images.githubusercontent.com/17591539/111061404-50d44380-84b4-11eb-98bc-9834acfb8f71.png)

**Comment by UnknownS1024** [comment]
i try VirtualBox distr Ubuntu experiment binary and testing other distributions run effekseer

**Comment by UnknownS1024** [comment]
@durswd virtualbox distr Ubuntu compiler binary works successfully experiment other distributions works well without errors everything is perfect :+1: 

`Effekseer`
![image](https://user-images.githubusercontent.com/17591539/111063913-3b661600-84c2-11eb-8703-b7121c472a34.png)

`EffekseerMaterialEditor`
![image](https://user-images.githubusercontent.com/17591539/111063990-afa0b980-84c2-11eb-855a-6cbb4d14799b.png)

`GodotEngine`
![image](https://user-images.githubusercontent.com/17591539/111064563-cdbbe900-84c5-11eb-9a05-745b5971b4a0.png)


@TheFourchette can give a binary file no need to compile run program everything works other linux distributions [download_1.6b2](https://drive.google.com/file/d/1OYJx_xsO0OBXLcY_hd5pFB6QvSE0-P_4/view?usp=sharing)

**Comment by durswd** [comment]
Did you install something in other distribution?

**Comment by UnknownS1024** [comment]
yes almost works fine :)
