### ISSUE TITLE
Cannot run on windows 10 with error "Unable to load DLL 'Viewer'"

### ISSUE THREAD

**Issue by ouyangtianhan** [effekseer/Effekseer#856]
Hi, I ran the latest released version: **1.62eWin**
But the effekseer.exe cannot start, and the error txt content is:
`
System.TypeInitializationException: The type initializer for 'Effekseer.swig.EffekseerNativePINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Viewer': 指定されたモジュールが見つかりません。 (Exception from HRESULT: 0x8007007E)
   at Effekseer.swig.EffekseerNativePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_EffekseerNative(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Effekseer.swig.EffekseerNativePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Effekseer.swig.EffekseerNativePINVOKE.SWIGExceptionHelper..ctor()
   at Effekseer.swig.EffekseerNativePINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Effekseer.swig.EffekseerNativePINVOKE.GetSystemLanguage()
   at Effekseer.Program.Exec(Boolean gui, String input, String output, String export, String format, Single magnification, Boolean materialCache)
   at Effekseer.Program.Main(String[] args)
`

Please help.

**Comment by ouyangtianhan** [comment]
Hi, I fixed this issue by copy the **Viewer.dll** into `C:\Windows\System32` & `C:\Windows\SysWOW64`, then **Restart my PC** and it fixed!
