### ISSUE TITLE
VS2022 run EffekseerEditor.csproj error 

### ISSUE THREAD

**Issue by yhy136** [effekseer/Effekseer#952]
after build, I use VS2022 run the Effeckseer.sln  int the build folder, however, when run the EffekseerEditor.csproj, i face a error:

---------------------------------------------------------------------------------------------------------------------------------
libpng error: Not a PNG file
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Effekseer.swig.EffekseerNativePINVOKE.GUIManager_AddFontFromFileTTF(System.Runtime.InteropServices.HandleRef, System.String, System.String, System.String, Single)
--------------------------------
   at Effekseer.swig.GUIManager.AddFontFromFileTTF(System.String, System.String, System.String, Single)
   at Effekseer.GUI.Manager.Update()
   at Effekseer.Application.Run()
   at Effekseer.Program.Exec(Boolean, System.String, System.String, System.String, System.String, Single, Boolean)
   at Effekseer.Program.Main(System.String[])
-------------------------------------------------------------------------------------------------------------------------------

i dont know why and how to solve, i will apprecaite who can help me, thank you

**Comment by durswd** [comment]
Did you clone with github lfs?

**Comment by yhy136** [comment]
> 

no, i clone the zip, and i download other files  by myself, i put them into  TestData, ResourceData, Downloads, Dev/Cpp/3rdParty folders. Is there any problem with this？

**Comment by yhy136** [comment]
i solve the problem, because the png ttf lib files are downloaded failed，they are 0KB, thank you.
